src/MvcMusicStore/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcMusicStore.Infrastructure;
using MvcMusicStore.Infrastructure.Core;
using MvcMusicStore.Model;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBus _bus;
        private readonly ICartStoreService _cartStoreService;
        private readonly MusicStoreEntities _storeDb = new MusicStoreEntities();

        public ShoppingCartController(IBus bus, ICartStoreService cartStoreService)
        {
            _bus = bus;
            _cartStoreService = cartStoreService;
        }

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(_cartStoreService);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public async Task<ActionResult> AddToCart(int id)
        {
            // Retrieve the album from the database
            Album addedAlbum = _storeDb.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            // Get the name of the album to display confirmation
            string albumName = _storeDb.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                          " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

src/MvcMusicStore/Controllers/StoreController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Model;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            List<Genre> genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            Genre genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            Album album = storeDB.Albums.Find(id);

            return View(album);
        }

        //
        // GET: /Store/GenreMenu

        //[ChildActionOnly]
        public ActionResult GenreMenu()
        {
            List<Genre> genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }
    }
}

src/MvcMusicStore/Views/Store/Browse.cshtml
@model MvcMusicStore.Model.Genre
 
@{
    ViewBag.Title = "Browse Albums";
}

<div class="row">
    <h3><em>@Model.Name</em> Albums</h3>

    @foreach (var album in Model.Albums)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <a href="@Url.Action("Details", "Store", new {id = album.AlbumId})">
                        <img alt="@album.Title" src="@album.AlbumArtUrl" />
                        <p>@album.Title</p>
                    </a>
                </div>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

src/MvcMusicStore/Views/Store/Details.cshtml
@model MvcMusicStore.Model.Album

@{
    ViewBag.Title = "Album - " + Model.Title;
}

<div class="row">
    <p></p>
    <div class="col-md-3">
        @{ Html.RenderAction("GenreMenu", "Store"); }
    </div>

    <div class="col-md-9">
        <div class="thumbnail-item">
            <img src="@Model.AlbumArtUrl" alt="@Model.Title">
            <div class="caption-full">
                <h4 class="pull-right">$@Model.Price</h4>
                <h4><a href="#">@Model.Title</a></h4>
                <p>@Model.Artist.Name</p>
                <p>@Model.Genre.Name</p>
                <p class="btn btn-default">
                    @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new {id = Model.AlbumId}, "")
                </p>

            </div>
            <div class="ratings">
                <p class="pull-right">3 reviews</p>
                <p>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    4.0 stars
                </p>
            </div>
        </div>

        <div class="well">

            <div class="text-right">
                <a class="btn btn-success">Leave a Review</a>
            </div>

            <hr>

            <div class="row">
                <div class="col-md-12">
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    Anonymous <span class="pull-right">10 days ago</span>
                    <p>This product was great in terms of quality. I would definitely buy another!</p>
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-md-12">
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    Anonymous <span class="pull-right">12 days ago</span>
                    <p>I've alredy ordered another one!</p>
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-md-12">
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    Anonymous <span class="pull-right">15 days ago</span>
                    <p>I've seen some better than this, but not at this price. I definitely recommend this item.</p>
                </div>
            </div>

        </div>

    </div>

</div>

src/MvcMusicStore/Views/Store/GenreMenu.cshtml
@model IEnumerable<MvcMusicStore.Model.Genre>

<div class="list-group">
    @foreach (var genre in Model)
    {
        @Html.ActionLink(genre.Name,
            "Browse", "Store",
            new {Genre = genre.Name}, new {Class = "list-group-item"})
    }
</div>

src/MvcMusicStore/Views/Store/Index.cshtml
@model IEnumerable<MvcMusicStore.Model.Genre>
@{
    ViewBag.Title = "Store";
}
<h3>Browse Genres</h3>

<p>
    Select from @Model.Count() genres:</p>
<ul>
    @foreach (var genre in Model)
    {
        <li>@Html.ActionLink(genre.Name, "Browse", new {genre = genre.Name})</li>
    }
</ul>