src/MvcMusicStore/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using MvcMusicStore.Model;

namespace MvcMusicStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

src/MvcMusicStore/Controllers/CheckoutController.cs
using MvcMusicStore.CQRS.Commands;
using MvcMusicStore.Infrastructure.Core;
using MvcMusicStore.Model;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class CheckoutController : Controller
    {
        private const string PromoCode = "FREE";
        private readonly IBus _bus;

        public CheckoutController(IBus bus)
        {
            _bus = bus;
        }

        public ActionResult AddressAndPayment()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            try
            {
                if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }

                await _bus.SendAsync(
                    new PlaceOrderCommand
                    {
                        UserName = User.Identity.Name,
                        OrderInfo = order
                    });

                return RedirectToAction("Complete");
            }
            catch (Exception ex)
            {
                return View(order);
            }
        }

        public ActionResult Complete()
        {
            return View();
        }
    }
}

src/MvcMusicStore/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcMusicStore.Infrastructure;
using MvcMusicStore.Infrastructure.Core;
using MvcMusicStore.Model;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBus _bus;
        private readonly ICartStoreService _cartStoreService;
        private readonly MusicStoreEntities _storeDb = new MusicStoreEntities();

        public ShoppingCartController(IBus bus, ICartStoreService cartStoreService)
        {
            _bus = bus;
            _cartStoreService = cartStoreService;
        }

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(_cartStoreService);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public async Task<ActionResult> AddToCart(int id)
        {
            // Retrieve the album from the database
            Album addedAlbum = _storeDb.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            // Get the name of the album to display confirmation
            string albumName = _storeDb.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                          " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            ShoppingCart cart = ShoppingCart.GetCart(_cartStoreService);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

src/MvcMusicStore/Controllers/StoreController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Model;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            List<Genre> genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            Genre genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            Album album = storeDB.Albums.Find(id);

            return View(album);
        }

        //
        // GET: /Store/GenreMenu

        //[ChildActionOnly]
        public ActionResult GenreMenu()
        {
            List<Genre> genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }
    }
}

src/MvcMusicStore/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Cart (" + ViewData["CartCount"] + ")",
    "Index",
    "ShoppingCart",
    new {id = "cart-status"})

src/MvcMusicStore/Views/ShoppingCart/Index.cshtml
@model MvcMusicStore.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<br/>
<div class="alert alert-info"><em>Review</em> your cart:</div>

<div id="update-message">
</div>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        @if (Model.CartItems.Count > 0)
        {
            <p class="btn btn-default">
                @Html.ActionLink("Checkout >>", "AddressAndPayment", "Checkout")
            </p>
        }
    </div>
    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Album Name</th>
                <th>Price (each)</th>
                <th>Quantity</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr id="row-@item.RecordId">
                    <td>
                        @Html.ActionLink(item.Album.Title, "Details", "Store", new {id = item.AlbumId}, null)
                    </td>
                    <td>
                        @item.Album.Price
                    </td>
                    <td id="item-count-@item.RecordId">
                        @item.Count
                    </td>
                    <td>
                        <a href="#" class="RemoveLink" data-id="@item.RecordId">Remove from cart</a>
                    </td>
                </tr>
            }
            <tr>
                <td>
                    Total
                </td>
                <td>
                    @Model.CartTotal
                </td>
                <td>
                </td>
                <td>
                   
                </td>
            </tr>
        </tbody>
    </table>
</div>